# Generated by Django 5.2.5 on 2025-08-16 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('technician', 'Technicien'), ('manager', 'Manager'), ('user', 'Utilisateur')], default='user', help_text="Rôle de l'utilisateur dans le système", max_length=20, verbose_name='Rôle')),
                ('photo', models.ImageField(blank=True, default='profile_photos/default.png', help_text="Photo de profil de l'utilisateur (optionnel)", null=True, upload_to='profile_photos/', verbose_name='Photo de profil')),
                ('phone', models.CharField(blank=True, help_text="Numéro de téléphone de l'utilisateur", max_length=20, verbose_name='Téléphone')),
                ('department', models.CharField(choices=[('it', 'Informatique'), ('hr', 'Ressources Humaines'), ('finance', 'Finance'), ('operations', 'Opérations'), ('support', 'Support Client'), ('other', 'Autre')], default='other', help_text="Département d'affectation", max_length=20, verbose_name='Département')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.OneToOneField(help_text="Référence vers l'utilisateur Django associé", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
                'ordering': ['user__username'],
            },
        ),
    ]
